import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  type BeamInput, type ColumnInput, type FootingInput, type SlabInput,
  type BeamDesignResult, type ColumnDesignResult, type FootingDesignResult, type SlabDesignResult,
  type CostEstimate,
} from "@/lib/structural-calculations";
import { jsPDF } from "jspdf";
import { Download, FileText, FileCode, Loader2 } from "lucide-react";
import { toast } from "sonner";

interface ExportToolsProps {
  type: "beam" | "column" | "footing" | "slab";
  input: BeamInput | ColumnInput | FootingInput | SlabInput;
  result: BeamDesignResult | ColumnDesignResult | FootingDesignResult | SlabDesignResult;
  cost: CostEstimate;
}

export function ExportTools({ type, input, result, cost }: ExportToolsProps) {
  const [isExporting, setIsExporting] = useState(false);

  const generatePDF = async () => {
    setIsExporting(true);
    try {
      const pdf = new jsPDF();
      const margin = 20;
      let y = 20;
      const lh = 7;

      pdf.setFontSize(20);
      pdf.setFont("helvetica", "bold");
      pdf.text("Structura - IS Code Design Report", margin, y);
      y += 10;
      pdf.setFontSize(14);
      pdf.text(`${type.charAt(0).toUpperCase() + type.slice(1)} Design (IS 456:2000)`, margin, y);
      y += 10;
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, margin, y);
      y += 12;

      // Input params
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Input Parameters", margin, y);
      y += 8;
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");

      const addParams = (params: string[]) => {
        params.forEach(p => { pdf.text(p, margin, y); y += lh; });
      };

      if (type === "beam") {
        const b = input as BeamInput;
        addParams([`Beam Type: ${b.beamType || "simply_supported"}`, `Span: ${b.spanLength} m`, `Width: ${b.width} mm`, `Depth: ${b.depth} mm`, `DL: ${b.deadLoad} kN/m`, `LL: ${b.liveLoad} kN/m`, `Concrete: ${b.concreteGrade}`, `Steel: ${b.steelGrade}`]);
      } else if (type === "column") {
        const c = input as ColumnInput;
        addParams([`End Condition: ${c.endCondition || "fixed_fixed"}`, `Height: ${c.height} m`, `Width: ${c.width} mm`, `Depth: ${c.depth} mm`, `Pu: ${c.axialLoad} kN`, `Mx: ${c.momentX} kNm`, `My: ${c.momentY} kNm`, `Concrete: ${c.concreteGrade}`, `Steel: ${c.steelGrade}`]);
      } else if (type === "footing") {
        const f = input as FootingInput;
        addParams([`Col Width: ${f.columnWidth} mm`, `Col Depth: ${f.columnDepth} mm`, `Axial Load: ${f.axialLoad} kN`, `SBC: ${f.soilBearingCapacity} kN/m2`, `Concrete: ${f.concreteGrade}`, `Steel: ${f.steelGrade}`]);
      } else {
        const s = input as SlabInput;
        addParams([`Short Span Lx: ${s.spanLx} m`, `Long Span Ly: ${s.spanLy} m`, `Live Load: ${s.liveLoad} kN/m2`, `Floor Finish: ${s.floorFinish} kN/m2`, `Edge: ${s.edgeCondition}`, `Concrete: ${s.concreteGrade}`, `Steel: ${s.steelGrade}`]);
      }

      y += 5;

      // Step-by-step calculations
      const steps = (result as any).steps;
      if (steps && steps.length > 0) {
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "bold");
        pdf.text("Step-by-Step Calculations", margin, y);
        y += 8;
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "normal");

        for (const step of steps) {
          if (y > 260) { pdf.addPage(); y = 20; }
          pdf.setFont("helvetica", "bold");
          pdf.text(`${step.label}${step.clause ? ` [${step.clause}]` : ""}`, margin, y);
          y += 5;
          pdf.setFont("helvetica", "normal");
          pdf.text(step.formula, margin + 5, y); y += 5;
          pdf.text(step.substitution, margin + 5, y); y += 5;
          pdf.setFont("helvetica", "bold");
          pdf.text(step.result, margin + 5, y); y += 7;
          pdf.setFont("helvetica", "normal");
        }
      }

      y += 5;
      if (y > 240) { pdf.addPage(); y = 20; }

      // Cost
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Cost Estimate", margin, y);
      y += 8;
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      Object.entries(cost.materials).forEach(([mat, data]) => {
        pdf.text(`${mat}: ${data.quantity} ${data.unit} x Rs.${data.rate} = Rs.${data.cost.toLocaleString()}`, margin, y);
        y += lh;
      });
      pdf.text(`Labor (35%): Rs.${cost.labor.toLocaleString()}`, margin, y); y += lh;
      pdf.setFont("helvetica", "bold");
      pdf.text(`Total: Rs.${cost.total.toLocaleString()}`, margin, y);

      pdf.setFontSize(8);
      pdf.setFont("helvetica", "italic");
      pdf.text("Generated by Structura - IS 456:2000 Compliant Design", margin, pdf.internal.pageSize.getHeight() - 10);

      pdf.save(`structura-${type}-design-${Date.now()}.pdf`);
      toast.success("PDF exported successfully!");
    } catch {
      toast.error("Failed to export PDF");
    } finally {
      setIsExporting(false);
    }
  };

  const generateDXF = () => {
    let dxf = "0\nSECTION\n2\nENTITIES\n";
    if (type === "beam") {
      const b = input as BeamInput;
      const length = b.spanLength * 1000;
      dxf += `0\nLINE\n8\nBEAM\n10\n0\n20\n0\n11\n${length}\n21\n0\n`;
      dxf += `0\nLINE\n8\nBEAM\n10\n${length}\n20\n0\n11\n${length}\n21\n${b.depth}\n`;
      dxf += `0\nLINE\n8\nBEAM\n10\n${length}\n20\n${b.depth}\n11\n0\n21\n${b.depth}\n`;
      dxf += `0\nLINE\n8\nBEAM\n10\n0\n20\n${b.depth}\n11\n0\n21\n0\n`;
    } else if (type === "slab") {
      const s = input as SlabInput;
      const lx = s.spanLx * 1000;
      const ly = s.spanLy * 1000;
      dxf += `0\nLINE\n8\nSLAB\n10\n0\n20\n0\n11\n${ly}\n21\n0\n`;
      dxf += `0\nLINE\n8\nSLAB\n10\n${ly}\n20\n0\n11\n${ly}\n21\n${lx}\n`;
      dxf += `0\nLINE\n8\nSLAB\n10\n${ly}\n20\n${lx}\n11\n0\n21\n${lx}\n`;
      dxf += `0\nLINE\n8\nSLAB\n10\n0\n20\n${lx}\n11\n0\n21\n0\n`;
    } else if (type === "column") {
      const c = input as ColumnInput;
      dxf += `0\nLINE\n8\nCOLUMN\n10\n0\n20\n0\n11\n${c.width}\n21\n0\n`;
      dxf += `0\nLINE\n8\nCOLUMN\n10\n${c.width}\n20\n0\n11\n${c.width}\n21\n${c.depth}\n`;
      dxf += `0\nLINE\n8\nCOLUMN\n10\n${c.width}\n20\n${c.depth}\n11\n0\n21\n${c.depth}\n`;
      dxf += `0\nLINE\n8\nCOLUMN\n10\n0\n20\n${c.depth}\n11\n0\n21\n0\n`;
    } else {
      const fRes = result as FootingDesignResult;
      dxf += `0\nLINE\n8\nFOOTING\n10\n0\n20\n0\n11\n${fRes.dimensions.length}\n21\n0\n`;
      dxf += `0\nLINE\n8\nFOOTING\n10\n${fRes.dimensions.length}\n20\n0\n11\n${fRes.dimensions.length}\n21\n${fRes.dimensions.width}\n`;
      dxf += `0\nLINE\n8\nFOOTING\n10\n${fRes.dimensions.length}\n20\n${fRes.dimensions.width}\n11\n0\n21\n${fRes.dimensions.width}\n`;
      dxf += `0\nLINE\n8\nFOOTING\n10\n0\n20\n${fRes.dimensions.width}\n11\n0\n21\n0\n`;
    }
    dxf += "0\nENDSEC\n0\nEOF\n";
    const blob = new Blob([dxf], { type: "application/dxf" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `structura-${type}-${Date.now()}.dxf`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("DXF file exported!");
  };

  return (
    <Card variant="default">
      <CardHeader className="pb-2">
        <CardTitle className="text-base flex items-center gap-2">
          <Download className="w-4 h-4 text-accent" />Export Options
        </CardTitle>
      </CardHeader>
      <CardContent className="flex gap-3">
        <Button variant="outline" className="flex-1" onClick={generatePDF} disabled={isExporting}>
          {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
          Export PDF
        </Button>
        <Button variant="outline" className="flex-1" onClick={generateDXF}>
          <FileCode className="w-4 h-4" />Export DXF
        </Button>
      </CardContent>
    </Card>
  );
}
